name: chapter1-co2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - pyarrow
  - xarray
  - netcdf4
  - geopandas
  - pyproj
  - rasterio
  - matplotlib
  - scikit-learn
  - requests
  - cdsapi>=0.7.7
  - ruff
  - pytest
