name: chapter1-co2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - xarray
  - netcdf4
  - matplotlib
  - seaborn
  - statsmodels
  - scikit-learn
  - requests
  - pyyaml
  - pip
  - pip:
      - filterpy
      - pykalman
      - ipython
